// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/base/BuildInfo

#ifndef org_chromium_base_BuildInfo_JNI
#define org_chromium_base_BuildInfo_JNI

#include <jni.h>

#include "base/android/jni_android.h"
#include "base/android/scoped_java_ref.h"
#include "base/basictypes.h"
#include "base/logging.h"

using base::android::ScopedJavaLocalRef;

// Step 1: forward declarations.
namespace {
const char kBuildInfoClassPath[] = "org/chromium/base/BuildInfo";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_BuildInfo_clazz = NULL;
}  // namespace

// Step 2: method stubs.

static base::subtle::AtomicWord g_BuildInfo_getDevice = 0;
static ScopedJavaLocalRef<jstring> Java_BuildInfo_getDevice(JNIEnv* env) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BuildInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BuildInfo_clazz,
      "getDevice",

"("
")"
"Ljava/lang/String;",
      &g_BuildInfo_getDevice);

  jstring ret =
    static_cast<jstring>(env->CallStaticObjectMethod(g_BuildInfo_clazz,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_BuildInfo_getBrand = 0;
static ScopedJavaLocalRef<jstring> Java_BuildInfo_getBrand(JNIEnv* env) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BuildInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BuildInfo_clazz,
      "getBrand",

"("
")"
"Ljava/lang/String;",
      &g_BuildInfo_getBrand);

  jstring ret =
    static_cast<jstring>(env->CallStaticObjectMethod(g_BuildInfo_clazz,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_BuildInfo_getAndroidBuildId = 0;
static ScopedJavaLocalRef<jstring> Java_BuildInfo_getAndroidBuildId(JNIEnv* env)
    {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BuildInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BuildInfo_clazz,
      "getAndroidBuildId",

"("
")"
"Ljava/lang/String;",
      &g_BuildInfo_getAndroidBuildId);

  jstring ret =
    static_cast<jstring>(env->CallStaticObjectMethod(g_BuildInfo_clazz,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_BuildInfo_getAndroidBuildFingerprint = 0;
static ScopedJavaLocalRef<jstring>
    Java_BuildInfo_getAndroidBuildFingerprint(JNIEnv* env) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BuildInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BuildInfo_clazz,
      "getAndroidBuildFingerprint",

"("
")"
"Ljava/lang/String;",
      &g_BuildInfo_getAndroidBuildFingerprint);

  jstring ret =
    static_cast<jstring>(env->CallStaticObjectMethod(g_BuildInfo_clazz,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_BuildInfo_getDeviceModel = 0;
static ScopedJavaLocalRef<jstring> Java_BuildInfo_getDeviceModel(JNIEnv* env) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BuildInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BuildInfo_clazz,
      "getDeviceModel",

"("
")"
"Ljava/lang/String;",
      &g_BuildInfo_getDeviceModel);

  jstring ret =
    static_cast<jstring>(env->CallStaticObjectMethod(g_BuildInfo_clazz,
      method_id));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_BuildInfo_getPackageVersionCode = 0;
static ScopedJavaLocalRef<jstring> Java_BuildInfo_getPackageVersionCode(JNIEnv*
    env, jobject context) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BuildInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BuildInfo_clazz,
      "getPackageVersionCode",

"("
"Landroid/content/Context;"
")"
"Ljava/lang/String;",
      &g_BuildInfo_getPackageVersionCode);

  jstring ret =
    static_cast<jstring>(env->CallStaticObjectMethod(g_BuildInfo_clazz,
      method_id, context));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_BuildInfo_getPackageVersionName = 0;
static ScopedJavaLocalRef<jstring> Java_BuildInfo_getPackageVersionName(JNIEnv*
    env, jobject context) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BuildInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BuildInfo_clazz,
      "getPackageVersionName",

"("
"Landroid/content/Context;"
")"
"Ljava/lang/String;",
      &g_BuildInfo_getPackageVersionName);

  jstring ret =
    static_cast<jstring>(env->CallStaticObjectMethod(g_BuildInfo_clazz,
      method_id, context));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

static base::subtle::AtomicWord g_BuildInfo_getPackageLabel = 0;
static ScopedJavaLocalRef<jstring> Java_BuildInfo_getPackageLabel(JNIEnv* env,
    jobject context) {
  /* Must call RegisterNativesImpl()  */
  DCHECK(g_BuildInfo_clazz);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_BuildInfo_clazz,
      "getPackageLabel",

"("
"Landroid/content/Context;"
")"
"Ljava/lang/String;",
      &g_BuildInfo_getPackageLabel);

  jstring ret =
    static_cast<jstring>(env->CallStaticObjectMethod(g_BuildInfo_clazz,
      method_id, context));
  base::android::CheckException(env);
  return ScopedJavaLocalRef<jstring>(env, ret);
}

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {

  g_BuildInfo_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetUnscopedClass(env, kBuildInfoClassPath)));
  return true;
}

#endif  // org_chromium_base_BuildInfo_JNI
